export const sampleReportData = [
    {
        id: 1,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 2,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 3,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 4,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 5,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 6,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 7,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 8,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 9,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
    },
    {
        id: 10,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
    },
    {
        id: 11,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 12,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 13,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 14,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
    {
        id: 15,
        reportDate: '2020-09-11',
        target: 'POST',
        reporter: '우진택',
        author: '나쁜남좌',
        type: '폭력,약탈행위',
        status: '대기',
        solvedDate: '2023-05-17',
    },
];
