import CheckBox from '@/components/commons/CheckBox';
import { decrement, increment } from '@/store/exampleSlice';
import { RootState } from '@/store/store';
import Head from 'next/head';
import { useDispatch, useSelector } from 'react-redux';

export default function Home() {
    const reduxTest = useSelector((state: RootState) => state.example.value);
    const dispatch = useDispatch();

    return (
        <>
            <Head>
                <title>Boilerplate</title>
                <meta
                    name="description"
                    content="Generated by create boilerplate"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>hello world! {reduxTest}</div>
            <button
                onClick={() => {
                    dispatch(increment());
                }}
            >
                +
            </button>
            <button
                onClick={() => {
                    dispatch(decrement());
                }}
            >
                -
            </button>
            {/* 체크박스 테스트 */}
            <CheckBox
                label={'안녕하세요'}
                labelPosition={'left'}
                fontSize={'13px'}
                fontColor={'gray'}
                boxSize={'small'}
                accentColor={'limegreen'}
                borderSize={'2px'}
                borderColor={'lightgray'}
                radius={'4px'}
            />
        </>
    );
}
